# Generated by Django 4.2.11 on 2024-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(choices=[(1, 'Каждый день'), (7, 'Каждую неделю')], default=1, verbose_name='Периодичность'),
        ),
    ]
